export enum Role {
  SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ADMIN = 'ROLE_ADMIN',
  MANAGER = 'ROLE_MANAGER',
  USER = 'ROLE_USER',
  HR = 'ROLE_HR',
  DOCTOR = 'ROLE_DOCTOR',
  ASSISTANT = 'ROLE_ASSISTANT'
}
